version: '3.8'

services:
  ml-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./models:/app/models
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=development
    command: python -m flask run --host=0.0.0.0 --port=5000